---
product_list:
- product_type: Sports
  products:
  - products/archery.md
  - products/badminton.md
  - products/baseball.md
  - products/basketball.md
  - products/beach-volleyball.md
  - products/bowling.md
  - products/boxing.md
  - products/broomball.md
  - products/coaching.md
  - products/cross-country-skiing.md
  - products/cycling.md
  - products/darts.md
  - products/disc-golf.md
  - products/field-marking.md
  - products/floor-hockey.md
  - products/football.md
  - products/futsal.md
  - products/games.md
  - products/golf.md
  - products/gymnastics.md
  - products/handball.md
  - products/hockey.md
  - products/juggling.md
  - products/lacrosse.md
  - products/made-in-canada.md
  - products/marine-supplies.md
  - products/martial-arts.md
  - products/officials-equipment.md
  - products/orienteering.md
  - products/pe-equipment.md
  - products/parkour.md
  - products/pickleball.md
  - products/racquetball.md
  - products/rhythmic-gymnastics.md
  - products/ringette.md
  - products/rock-wall-climbing.md
  - products/rugby.md
  - products/snowshoes.md
  - products/soccer.md
  - products/softball.md
  - products/squash.md
  - products/table-tennis.md
  - products/tennis.md
  - products/track-field.md
  - products/ultimate.md
  - products/volleyball.md
  - products/water-polo.md
  - products/weight-lifting.md
- product_type: Attire & Accessories
  products:
  - products/bags-totes-duffels.md
  - products/camouflage.md
  - products/headwear.md
  - products/hoodies.md
  - products/jackets.md
  - products/jerseys.md
  - products/pants.md
  - "/products/ppe-facemasks-neck-gaiters-adult-youth.md"
  - products/shirts.md
  - products/shorts.md
  - products/socks.md
  - products/sublimation.md
  - products/sweaters.md
  - products/track-suits.md
  - products/workwear.md
- product_type: Equipment
  products:
  - products/chairs.md
  - products/dividers.md
  - products/floor-covering.md
  - products/helmet-decals.md
  - products/inflators.md
  - products/misc.md
  - products/nets.md
  - products/officials-equipment.md
  - products/pe-equipment.md
  - products/pinnies.md
  - products/protective-pads-and-wall-padding.md
  - products/scoreboards.md
  - products/score-tables.md
  - products/seating.md
  - products/storage-solutions.md
  - products/training-supplies.md
  - products/whistles.md
- product_type: Promotional Items
  products:
  - products/aprons.md
  - products/auto-and-travel.md
  - products/bags-totes-duffels.md
  - products/banners.md
  - products/blankets.md
  - products/canopies.md
  - products/cleaning-supplies.md
  - products/drinkware.md
  - products/event-planning.md
  - products/eyewear.md
  - products/gift-sets.md
  - products/health-fitness.md
  - products/home.md
  - products/lanyards.md
  - products/notebooks.md
  - products/pens.md
  - products/pets.md
  - products/plush-novelties.md
  - products/ribbons.md
  - products/safety.md
  - products/table-covers.md
  - products/tech-items.md
  - products/tissues.md
  - products/tools-lights-keytags.md
  - products/towels.md
  - products/umbrellas.md
  - products/wind-flags.md
