---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Sections
- type: directory
  path: brands
  label: Brands
  create: documents
  match: "**/*"
  exclude: "**/index.md"
  new_doc_ext: md
  templates:
  - brand
- type: directory
  path: catalogue
  label: Categories
  create: documents
  match: "**/*"
  exclude: "**/index.md"
  new_doc_ext: md
  templates:
  - category
- type: document
  path: clearance.md
  label: Clearance
- type: document
  path: gallery.md
  label: Gallery
- type: document
  path: meet-the-team.md
  label: Meet the Team
- type: document
  path: testimonials.md
  label: Testimonials
- type: heading
  label: Lists
- type: document
  path: _data/categories.yml
  label: Category list
- type: heading
  label: Documentation
- type: document
  path: _data/instructions.md
  label: Instructions
  read_only: true
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=development
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
