---
label: Product
hide_body: true
fields:
- type: text
  name: layout
  label: Layout
  hidden: true
  description: 'Layout should be: product'
  config:
    required: true
  default: product
- type: text
  name: title
  label: Title
  hidden: false
- type: text
  name: permalink
  label: Permalink
  hidden: false
  description: 'Permalink should be: "/products/TITLE" where TITLE is the lowercased
    version of the title. Example: Beach Volleyball would be "/products/beach-volleyball".'
  config:
    required: false
  default: "/products/TITLE"
- type: list
  name: products
  label: Products
  description: A list of products your suppliers offer in this category
  config:
    use_select: false
    source:
      type: documents
- name: photos
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: photo
    type: file
    config:
      maxSize: 64
    label: Photo
  config:
    min: 
    max: 
    labelField: 
  label: Photos
- name: promotions
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
    description: The title of the product.
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
    description: The image of the product
  - name: price
    type: number
    label: Price
    description: The price of the product
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  - name: description
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Description
    description: The description of the product.
  config:
    min: 
    max: 
    labelField: 
  label: Promotions
  description: The products on clearance
pages:
- products/aprons.md
- products/aprons.md
- products/badminton.md
- products/badminton.md
- products/bags-totes-duffels.md
- products/bags-totes-duffels.md
- products/banners.md
- products/banners.md
- products/baseball.md
- products/baseball.md
- products/basketball.md
- products/basketball.md
- products/beach-volleyball.md
- products/beach-volleyball.md
- products/blankets.md
- products/blankets.md
- products/bowling.md
- products/bowling.md
- products/boxing.md
- products/boxing.md
- products/broomball.md
- products/broomball.md
- products/camouflage.md
- products/camouflage.md
- products/canopies.md
- products/canopies.md
- products/chairs.md
- products/chairs.md
- products/cleaning-supplies.md
- products/cleaning-supplies.md
- products/coaching.md
- products/coaching.md
- products/cross-country-skiing.md
- products/cross-country-skiing.md
- products/curling.md
- products/curling.md
- products/cycling.md
- products/cycling.md
- products/darts.md
- products/darts.md
- products/disc-golf.md
- products/disc-golf.md
- products/dividers.md
- products/dividers.md
- products/drinkware.md
- products/drinkware.md
- products/event-planning.md
- products/event-planning.md
- products/eyewear.md
- products/eyewear.md
- products/field-marking.md
- products/field-marking.md
- products/first-aid.md
- products/first-aid.md
- products/floor-covering.md
- products/floor-covering.md
- products/floor-hockey.md
- products/floor-hockey.md
- products/food-gifts.md
- products/food-gifts.md
- products/football.md
- products/football.md
- products/futsal.md
- products/futsal.md
- products/games.md
- products/games.md
- products/gift-sets.md
- products/gift-sets.md
- products/golf.md
- products/golf.md
- products/gymnastics.md
- products/gymnastics.md
- products/handball.md
- products/handball.md
- products/headwear.md
- products/headwear.md
- products/health-fitness.md
- products/health-fitness.md
- products/helmet-decals.md
- products/helmet-decals.md
- products/hockey.md
- products/hockey.md
- products/home.md
- products/home.md
- products/hoodies.md
- products/hoodies.md
- products/inflators.md
- products/inflators.md
- products/jackets.md
- products/jackets.md
- products/jerseys.md
- products/jerseys.md
- products/juggling.md
- products/juggling.md
- products/lacrosse.md
- products/lacrosse.md
- products/lanyards.md
- products/lanyards.md
- products/luggage.md
- products/luggage.md
- products/made-in-canada.md
- products/made-in-canada.md
- products/marine-supplies.md
- products/marine-supplies.md
- products/martial-arts.md
- products/martial-arts.md
- products/misc.md
- products/misc.md
- products/nets.md
- products/nets.md
- products/notebooks.md
- products/notebooks.md
- products/officials-equipment.md
- products/officials-equipment.md
- products/orienteering.md
- products/orienteering.md
- products/pants.md
- products/pants.md
- products/parkour.md
- products/parkour.md
- products/pe-equipment.md
- products/pe-equipment.md
- products/pens.md
- products/pens.md
- products/pets.md
- products/pets.md
- products/pickleball.md
- products/pickleball.md
- products/pinnies.md
- products/pinnies.md
- products/plush-novelties.md
- products/plush-novelties.md
- products/posts.md
- products/posts.md
- products/racquetball.md
- products/racquetball.md
- products/rhythmic-gymnastics.md
- products/rhythmic-gymnastics.md
- products/ribbons.md
- products/ribbons.md
- products/ringette.md
- products/ringette.md
- products/rock-wall-climbing.md
- products/rock-wall-climbing.md
- products/rugby.md
- products/rugby.md
- products/safety.md
- products/safety.md
- products/scoreboards.md
- products/scoreboards.md
- products/seating.md
- products/seating.md
- products/shirts.md
- products/shirts.md
- products/shorts.md
- products/shorts.md
- products/snow-recreation.md
- products/snowshoes.md
- products/snowshoes.md
- products/soccer.md
- products/soccer.md
- products/socks.md
- products/socks.md
- products/softball.md
- products/softball.md
- products/squash.md
- products/squash.md
- products/storage-solutions.md
- products/storage-solutions.md
- products/sublimation.md
- products/sublimation.md
- products/sweaters.md
- products/sweaters.md
- products/table-covers.md
- products/table-covers.md
- products/table-tennis.md
- products/table-tennis.md
- products/tech-items.md
- products/tech-items.md
- products/tennis.md
- products/tennis.md
- products/tissues.md
- products/tissues.md
- products/tools-lights-keytags.md
- products/tools-lights-keytags.md
- products/towels.md
- products/towels.md
- products/track-field.md
- products/track-field.md
- products/track-suits.md
- products/track-suits.md
- products/training-supplies.md
- products/training-supplies.md
- products/ultimate.md
- products/ultimate.md
- products/umbrellas.md
- products/umbrellas.md
- products/volleyball.md
- products/volleyball.md
- products/water-polo.md
- products/water-polo.md
- products/weight-lifting.md
- products/weight-lifting.md
- products/whistles.md
- products/whistles.md
- products/wind-flags.md
- products/wind-flags.md
- products/workwear.md
- products/workwear.md
